# Generated by Django 2.1.7 on 2019-02-17 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compillerwebsite', '0003_auto_20190217_1316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='title',
        ),
    ]
