# Generated by Django 2.1.7 on 2019-02-17 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compillerwebsite', '0004_remove_grade_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewsArticle',
        ),
    ]
